name: depoly

on:
  push:
    branches: [main]
    
jobs:
  Depoly:
    runs-on: ubuntu-16.04
    
    steps:
      - uses: actions/checkout@v3
      - name: Script - git pull
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.SSH_PASSWORD }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          script: cd /home/sinkj98/datamoa_be/ && git checkout . && git pull
      - name: Script - server reload
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.SSH_PASSWORD }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.PORT }}
          script: cd /home/sinkj98/datamoa_be/ && docker exec Node_Server pm2 reload server.js
